version: '3.5'

services:

  server:
    volumes:
      - ./src:/usr/app/src:ro
      - ./test:/usr/app/test:ro
      - ./coverage:/usr/app/coverage:rw
      - ./package.json:/usr/app/package.json:rw #won't work with CI because of host docker's engine being shared
