version: '3.5'

services:

  server:
    image: ${PROJECT_NAME}:dev
    container_name: ${PROJECT_NAME}_server
    hostname: ${PROJECT_NAME}_server
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 90:3000
    depends_on:
      - db

  db:
    image: ${PROJECT_NAME}_db:dev
    container_name: ${PROJECT_NAME}_db
    hostname: ${PROJECT_NAME}_db
    build:
      context: .
      dockerfile: Dockerfile-sql
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: solutec
      POSTGRES_USER: devops